import type { CreatePriceListImportInput } from './contracts';

export const inventorySeedFixtures = {
  suppliers: [
    {
      key: 'VND_001',
      name: 'Cape Stone Works',
      logo: 'https://picsum.photos/seed/capestone/100/100',
      status: 'Active',
      type: 'Manufacturer',
      capabilities: ['Cladding', 'Architectural Stone', 'Studio Renders'],
      region: 'South Africa / Western Cape',
      leadTimeDays: 7,
      leadTimeLabel: '5-7 Days',
      rating: 4.9,
      blocker: null,
      contacts: [
        { department: 'Sales', name: 'Liam Smit', email: 'sales@capestone.co.za', phone: '+27 21 555 0101', preferredChannel: 'Email' },
        { department: 'Dispatch', name: 'Tara Daniels', email: 'dispatch@capestone.co.za', phone: '+27 21 555 0102', preferredChannel: 'WhatsApp' },
      ],
      terms: { payment: '50% Deposit', delivery: 'Ex Works Cape Town', moq: 'No MOQ', currency: 'ZAR', incoterms: 'EXW' },
      performance: { onTimeDelivery: 97, qualityScore: 96, returnRate: 0.8, priceCompetitiveness: 84 },
      workflowMilestones: { onboarded: true, linkedToProducts: true, poIssued: true, dispatchReady: true, claimsVerified: true },
      orders: [{ id: 'PO-2026-010', date: '2026-03-18', status: 'Delivered', amount: 38200, type: 'PO' }],
      history: [{ date: '2026-03-20', action: 'Lead Time Updated', user: 'System', details: 'Cape Town route normalized to 5-7 days' }],
      locations: [
        {
          key: 'LOC_001',
          label: 'Cape Town Supplier Origin',
          type: 'Supplier Origin',
          country: 'South Africa',
          region: 'Western Cape',
          city: 'Cape Town',
          latitude: -33.9249,
          longitude: 18.4241,
        },
      ],
    },
    {
      key: 'VND_002',
      name: 'Karoo Brick Collective',
      logo: 'https://picsum.photos/seed/karoobrick/100/100',
      status: 'Active',
      type: 'Manufacturer',
      capabilities: ['Bricks', 'Face Brick', '2.5D Asset Production'],
      region: 'South Africa / Northern Cape',
      leadTimeDays: 10,
      leadTimeLabel: '7-10 Days',
      rating: 4.7,
      blocker: null,
      contacts: [
        { department: 'Sales', name: 'Mila van Zyl', email: 'trade@karoobrick.co.za', phone: '+27 53 555 2201', preferredChannel: 'Phone' },
        { department: 'Accounts', name: 'Rohan Meyer', email: 'accounts@karoobrick.co.za', phone: '+27 53 555 2202', preferredChannel: 'Email' },
      ],
      terms: { payment: 'Net 14', delivery: 'Delivered Gauteng', moq: '500 units', currency: 'ZAR', incoterms: 'DAP' },
      performance: { onTimeDelivery: 93, qualityScore: 94, returnRate: 1.4, priceCompetitiveness: 88 },
      workflowMilestones: { onboarded: true, linkedToProducts: true, poIssued: true, dispatchReady: true, claimsVerified: true },
      orders: [{ id: 'PO-2026-014', date: '2026-03-25', status: 'Confirmed', amount: 26500, type: 'PO' }],
      history: [{ date: '2026-03-21', action: 'Color Batch Approved', user: 'Sarah Chen', details: 'NFX rustic reference approved for campaign use' }],
      locations: [
        {
          key: 'LOC_002',
          label: 'Kimberley Dispatch Yard',
          type: 'Supplier Origin',
          country: 'South Africa',
          region: 'Northern Cape',
          city: 'Kimberley',
          latitude: -28.7282,
          longitude: 24.7499,
        },
      ],
    },
    {
      key: 'VND_003',
      name: 'Urban Paving Systems',
      logo: 'https://picsum.photos/seed/urbanpaving/100/100',
      status: 'Delayed',
      type: 'Distributor',
      capabilities: ['Paving', 'Road Kerbs', 'External Hardscape'],
      region: 'South Africa / Gauteng',
      leadTimeDays: 18,
      leadTimeLabel: '14-18 Days',
      rating: 4.1,
      blocker: 'Kiln maintenance delaying bevel paving output',
      contacts: [
        { department: 'Sales', name: 'Naledi Khumalo', email: 'orders@urbanpaving.co.za', phone: '+27 11 555 3401', preferredChannel: 'Email' },
      ],
      terms: { payment: 'COD for first order', delivery: 'Origin Johannesburg', moq: '1 pallet', currency: 'ZAR', incoterms: 'EXW' },
      performance: { onTimeDelivery: 78, qualityScore: 90, returnRate: 2.1, priceCompetitiveness: 91 },
      workflowMilestones: { onboarded: true, linkedToProducts: true, poIssued: true, dispatchReady: false, claimsVerified: true },
      orders: [{ id: 'PO-2026-017', date: '2026-03-28', status: 'Shipped', amount: 45100, type: 'PO' }],
      history: [{ date: '2026-03-29', action: 'Delay Alert', user: 'System', details: 'Bevel paving batches pushed by 4 days' }],
      locations: [
        {
          key: 'LOC_003',
          label: 'Johannesburg Hardscape Hub',
          type: 'Supplier Origin',
          country: 'South Africa',
          region: 'Gauteng',
          city: 'Johannesburg',
          latitude: -26.2041,
          longitude: 28.0473,
        },
      ],
    },
    {
      key: 'VND_004',
      name: 'Metro Block Industries',
      logo: 'https://picsum.photos/seed/metroblocks/100/100',
      status: 'Onboarding',
      type: 'Manufacturer',
      capabilities: ['Blocks', 'Breeze Blocks', 'Mould Development'],
      region: 'South Africa / KwaZulu-Natal',
      leadTimeDays: 0,
      leadTimeLabel: 'Awaiting onboarding',
      rating: 0,
      blocker: 'Supplier pack and banking details outstanding',
      contacts: [
        { department: 'Onboarding', name: 'Aiden Naidoo', email: 'onboarding@metroblocks.co.za', phone: '+27 31 555 4101', preferredChannel: 'Email' },
      ],
      terms: { payment: 'TBD', delivery: 'TBD', moq: 'TBD', currency: 'ZAR', incoterms: 'TBD' },
      performance: { onTimeDelivery: 0, qualityScore: 0, returnRate: 0, priceCompetitiveness: 0 },
      workflowMilestones: { onboarded: true, linkedToProducts: true, poIssued: false, dispatchReady: false, claimsVerified: false },
      orders: [],
      history: [{ date: '2026-03-30', action: 'Onboarding Started', user: 'Marcus Thorne', details: 'Awaiting final trade pack' }],
      locations: [
        {
          key: 'LOC_004',
          label: 'Durban Factory Gate',
          type: 'Supplier Origin',
          country: 'South Africa',
          region: 'KwaZulu-Natal',
          city: 'Durban',
          latitude: -29.8587,
          longitude: 31.0218,
        },
      ],
    },
  ],
  logisticsRateCards: [
    { key: 'RATE_001', supplierKey: 'VND_001', locationKey: 'LOC_001', currency: 'ZAR', costPerKm: 25, sellPricePerKm: 35, fixedFee: 0, minimumCharge: 0 },
    { key: 'RATE_002', supplierKey: 'VND_002', locationKey: 'LOC_002', currency: 'ZAR', costPerKm: 25, sellPricePerKm: 35, fixedFee: 0, minimumCharge: 0 },
    { key: 'RATE_003', supplierKey: 'VND_003', locationKey: 'LOC_003', currency: 'ZAR', costPerKm: 25, sellPricePerKm: 35, fixedFee: 0, minimumCharge: 0 },
    { key: 'RATE_004', supplierKey: 'VND_004', locationKey: 'LOC_004', currency: 'ZAR', costPerKm: 25, sellPricePerKm: 35, fixedFee: 0, minimumCharge: 0 },
  ],
  products: [
    {
      referenceId: 'PRD_101',
      publicSku: 'BTS-CLD-MOD-101',
      name: 'Travertine Horizon Cladding',
      category: 'Cladding',
      productType: 'Modern',
      finish: 'Travertine',
      collection: 'Horizon Line',
      tags: ['Cladding', 'Travertine', 'Facade'],
      status: 'Active',
      publishStatus: 'Published',
      pricingUnit: 'm2',
      sellPriceZar: 1245,
      primaryImageUrl: 'https://picsum.photos/seed/cladding_primary/800/800',
      galleryImageUrl: 'https://picsum.photos/seed/cladding_gallery/800/800',
      faceImageUrl: 'https://picsum.photos/seed/cladding_face/800/800',
      heroImageUrl: 'https://picsum.photos/seed/cladding_hero/1600/900',
      description: 'Linear travertine cladding system built for premium exterior walls and interior feature reveals.',
      marketingCopy: 'Architectural travertine with a calmer, longer rhythm for premium contemporary elevations.',
      latestTestReport: {
        name: 'travertine-horizon-lab-report.pdf',
        laboratoryName: 'BTS Materials Lab',
        methodStandard: 'SANS 1215 / Internal QA',
        reportReference: 'LAB-CLD-101-2026-03',
        testedAt: '2026-03-11T08:00:00.000Z',
        issuedAt: '2026-03-13T10:00:00.000Z',
      },
      specifications: {
        Material: 'Travertine Composite',
        Use: 'Wall Cladding',
        Pack: 'Boxed by coverage',
      },
      testResults: [
        { type: 'Water Absorption (%)', value: 6.8, unit: '%', notes: 'Average of latest approved sample set' },
        { type: 'Tested Length (mm)', value: 400, unit: 'mm' },
        { type: 'Tested Width (mm)', value: 30, unit: 'mm' },
        { type: 'Tested Height (mm)', value: 110, unit: 'mm' },
        { type: 'Dry Mass (kg)', value: 2.9, unit: 'kg' },
        { type: 'Breaking Load (kN)', value: 4.4, unit: 'kN' },
      ],
      dimensions: {
        lengthMm: 400,
        widthMm: 30,
        heightMm: 110,
        coverageOrientation: 'Length x Height',
        weightKg: 2.9,
      },
      packaging: {
        piecesPerPallet: 2000,
        boxesPerPallet: 40,
        palletsPerTruck: 24,
      },
      supplierLink: {
        supplierKey: 'VND_001',
        locationKey: 'LOC_001',
        unitCostZar: 790,
        leadTimeDays: 7,
        minimumOrderQuantity: 1,
        paymentTerms: '50% Deposit',
        incoterms: 'EXW',
      },
      purchaseOrders: [
        {
          key: 'PO-2026-101',
          supplierKey: 'VND_001',
          locationKey: 'LOC_001',
          status: 'Delivered',
          orderedAt: '2026-03-14T09:00:00.000Z',
          currency: 'ZAR',
          triggerSource: 'QUOTE_PAID',
          triggerReference: 'QTE-2026-CLD-101',
          lines: [{ publicSku: 'BTS-CLD-MOD-101', quantity: 38, unitCostZar: 790 }],
          receipt: { key: 'GRN-2026-101', receivedAt: '2026-03-18T11:00:00.000Z', status: 'Received', note: 'Completed supplier fulfillment' },
        },
      ],
      history: [
        { type: 'Product Created', occurredAt: '2026-03-01T10:00:00.000Z', action: 'Product Created', user: 'Inventory API', details: 'Seeded deterministic catalog product' },
        { type: 'Procurement Triggered', occurredAt: '2026-03-14T09:00:00.000Z', action: 'Quote Paid Procurement', user: 'Sales Engine', details: 'QTE-2026-CLD-101' },
      ],
      distributionChannels: [
        {
          channel: 'Meta Catalog',
          type: 'Catalog',
          connectionStatus: 'Connected',
          publicationStatus: 'Live',
          syncMode: 'API',
          externalCatalogId: 'meta-catalog-cladding-main',
          externalListingId: 'META-BTS-CLD-MOD-101',
          externalUrl: 'https://business.facebook.com/commerce/catalogs/meta-catalog-cladding-main',
          lastSyncedAt: '2026-04-01T13:20:00.000Z',
        },
        {
          channel: 'Google Merchant Center',
          type: 'Catalog',
          connectionStatus: 'Connected',
          publicationStatus: 'Live',
          syncMode: 'API',
          externalCatalogId: 'gmc-bts-main',
          externalListingId: 'online:en:ZA:BTS-CLD-MOD-101',
          externalUrl: 'https://merchants.google.com/mc/products/details?offerId=online:en:ZA:BTS-CLD-MOD-101',
          lastSyncedAt: '2026-04-01T13:32:00.000Z',
        },
        {
          channel: 'WhatsApp Catalog',
          type: 'Messaging',
          connectionStatus: 'Connected',
          publicationStatus: 'Live',
          syncMode: 'API',
          externalCatalogId: 'wa-bts-showroom',
          externalListingId: 'WA-BTS-CLD-MOD-101',
          lastSyncedAt: '2026-04-01T13:28:00.000Z',
        },
      ],
      assets: [
        { key: 'AST_101_PRIMARY', name: 'Travertine Horizon Primary', type: 'Image', role: 'primary_image', source: 'Direct Upload', protectionLevel: 'Protected Original', status: 'Approved', size: '8.4MB', img: 'https://picsum.photos/seed/cladding_primary/800/800', tags: ['Primary', 'Cladding'] },
        { key: 'AST_101_GALLERY', name: 'Travertine Horizon Gallery', type: 'Image', role: 'gallery_image', source: 'Direct Upload', protectionLevel: 'Managed Variant', status: 'Approved', size: '6.2MB', img: 'https://picsum.photos/seed/cladding_gallery/800/800', tags: ['Gallery', 'Coverage'] },
        { key: 'AST_101_FACE', name: 'Travertine Horizon Face', type: 'Image', role: 'face_image', source: 'Direct Upload', protectionLevel: 'Managed Variant', status: 'Approved', size: '4.9MB', img: 'https://picsum.photos/seed/cladding_face/800/800', tags: ['Face', 'Texture'] },
        { key: 'AST_101_HERO', name: 'Travertine Horizon Hero', type: 'Image', role: 'hero_image', source: 'Asset Library', protectionLevel: 'Publishable Variant', status: 'Approved', size: '3.1MB', img: 'https://picsum.photos/seed/cladding_hero/1600/900', tags: ['Hero', 'Storefront'] },
        { key: 'AST_101_25D', name: 'Travertine Horizon 2.5D', type: '2.5D Asset', role: 'asset_2_5d', source: 'Marketing Tool', protectionLevel: 'Managed Variant', status: 'Approved', size: '18.2MB', img: 'https://picsum.photos/seed/cladding_25d/800/800', tags: ['2.5D', 'Cutout'], is3DReady: true },
        { key: 'AST_101_3D', name: 'Travertine Horizon 3D', type: '3D Asset', role: 'asset_3d', source: 'Marketing Tool', protectionLevel: 'Protected Original', status: 'Review', size: '42.0MB', img: 'https://picsum.photos/seed/cladding_3d/800/800', tags: ['3D', 'PBR'], is3DReady: true, pipeline: { sourceUploaded: true, textureReady: true, previewAttached: true, modelReferenceAttached: true, conversionStatus: 'Processing' } },
        { key: 'AST_101_PROJECT', name: 'Travertine Horizon Project', type: 'Image', role: 'project_image', source: 'Community Submission', protectionLevel: 'Publishable Variant', status: 'Approved', size: '5.7MB', img: 'https://picsum.photos/seed/cladding_project/800/800', tags: ['Community', 'Project'] },
      ],
    },
    {
      referenceId: 'PRD_205',
      publicSku: 'BTS-BRK-NFX-205',
      name: 'Karoo Rustic NFX Brick',
      category: 'Bricks',
      productType: 'NFX',
      finish: 'Rustic',
      collection: 'Karoo Earth',
      tags: ['Brick', 'NFX', 'Rustic'],
      status: 'Active',
      publishStatus: 'Ready',
      pricingUnit: 'piece',
      sellPriceZar: 18.5,
      primaryImageUrl: 'https://picsum.photos/seed/brick_primary/800/800',
      galleryImageUrl: 'https://picsum.photos/seed/brick_gallery/800/800',
      faceImageUrl: 'https://picsum.photos/seed/brick_face/800/800',
      heroImageUrl: 'https://picsum.photos/seed/brick_hero/1600/900',
      description: 'Rustic NFX face brick for premium homes, hospitality courtyards, and warm external envelopes.',
      marketingCopy: 'An earth-toned NFX brick with enough tonal movement to feel premium without losing detailing discipline.',
      latestTestReport: {
        name: 'karoo-rustic-nfx-lab-report.pdf',
        laboratoryName: 'Clay Performance Lab',
        methodStandard: 'SANS 227',
        reportReference: 'LAB-BRK-205-2026-02',
        testedAt: '2026-02-24T08:00:00.000Z',
        issuedAt: '2026-02-26T11:00:00.000Z',
      },
      specifications: {
        Material: 'Clay Brick',
        Use: 'Face Brick',
        Pattern: 'Running Bond',
      },
      testResults: [
        { type: 'Compressive Strength (MPa)', value: 28.4, unit: 'MPa', notes: 'Mean compressive strength across approved batch' },
        { type: 'Water Absorption (%)', value: 8.2, unit: '%'},
        { type: 'Tested Length (mm)', value: 222, unit: 'mm' },
        { type: 'Tested Width (mm)', value: 106, unit: 'mm' },
        { type: 'Tested Height (mm)', value: 73, unit: 'mm' },
        { type: 'Dry Mass (kg)', value: 3.1, unit: 'kg' },
        { type: 'Wet Mass (kg)', value: 3.35, unit: 'kg' },
      ],
      dimensions: {
        lengthMm: 222,
        widthMm: 106,
        heightMm: 73,
        coverageOrientation: 'Length x Height',
        weightKg: 3.1,
      },
      packaging: {
        piecesPerPallet: 500,
        palletsPerTruck: 24,
      },
      supplierLink: {
        supplierKey: 'VND_002',
        locationKey: 'LOC_002',
        unitCostZar: 11.2,
        leadTimeDays: 10,
        minimumOrderQuantity: 500,
        paymentTerms: 'Net 14',
        incoterms: 'DAP',
      },
      purchaseOrders: [
        {
          key: 'PO-2026-205',
          supplierKey: 'VND_002',
          locationKey: 'LOC_002',
          status: 'Confirmed',
          orderedAt: '2026-03-26T08:30:00.000Z',
          currency: 'ZAR',
          triggerSource: 'QUOTE_PAID',
          triggerReference: 'QTE-2026-BRK-205',
          lines: [{ publicSku: 'BTS-BRK-NFX-205', quantity: 2400, unitCostZar: 11.2 }],
        },
      ],
      history: [
        { type: 'Product Created', occurredAt: '2026-03-02T10:00:00.000Z', action: 'Product Created', user: 'Inventory API' },
        { type: 'Asset Attached', occurredAt: '2026-03-08T12:00:00.000Z', action: '2.5D Asset Attached', user: 'Marketing Tool' },
      ],
      distributionChannels: [
        {
          channel: 'Meta Catalog',
          type: 'Catalog',
          connectionStatus: 'Connected',
          publicationStatus: 'Queued',
          syncMode: 'API',
          externalCatalogId: 'meta-catalog-bricks-main',
          externalListingId: 'META-BTS-BRK-NFX-205',
          lastSyncedAt: '2026-04-01T10:05:00.000Z',
        },
        {
          channel: 'Google Merchant Center',
          type: 'Catalog',
          connectionStatus: 'Connected',
          publicationStatus: 'Not Posted',
          syncMode: 'API',
          externalCatalogId: 'gmc-bts-main',
        },
        {
          channel: 'TikTok Shop',
          type: 'Marketplace',
          connectionStatus: 'Degraded',
          publicationStatus: 'Failed',
          syncMode: 'API',
          externalCatalogId: 'tts-bts-za',
          lastSyncedAt: '2026-04-01T09:55:00.000Z',
          lastSyncError: 'Variant packaging attributes were rejected by the destination schema.',
        },
      ],
      assets: [
        { key: 'AST_205_PRIMARY', name: 'Karoo Rustic Primary', type: 'Image', role: 'primary_image', source: 'Direct Upload', protectionLevel: 'Protected Original', status: 'Approved', size: '7.8MB', img: 'https://picsum.photos/seed/brick_primary/800/800', tags: ['Primary', 'Brick'] },
        { key: 'AST_205_GALLERY', name: 'Karoo Rustic Gallery', type: 'Image', role: 'gallery_image', source: 'Direct Upload', protectionLevel: 'Managed Variant', status: 'Approved', size: '5.4MB', img: 'https://picsum.photos/seed/brick_gallery/800/800', tags: ['Gallery', 'Brick'] },
        { key: 'AST_205_FACE', name: 'Karoo Rustic Face', type: 'Image', role: 'face_image', source: 'Direct Upload', protectionLevel: 'Managed Variant', status: 'Approved', size: '4.2MB', img: 'https://picsum.photos/seed/brick_face/800/800', tags: ['Face', 'Brick'] },
        { key: 'AST_205_HERO', name: 'Karoo Rustic Hero', type: 'Image', role: 'hero_image', source: 'Asset Library', protectionLevel: 'Publishable Variant', status: 'Approved', size: '2.9MB', img: 'https://picsum.photos/seed/brick_hero/1600/900', tags: ['Hero'] },
        { key: 'AST_205_25D', name: 'Karoo Rustic 2.5D', type: '2.5D Asset', role: 'asset_2_5d', source: 'Marketing Tool', protectionLevel: 'Managed Variant', status: 'Approved', size: '14.1MB', img: 'https://picsum.photos/seed/brick_25d/800/800', tags: ['2.5D'] },
        { key: 'AST_205_PROJECT', name: 'Karoo Rustic Project', type: 'Image', role: 'project_image', source: 'Community Submission', protectionLevel: 'Publishable Variant', status: 'Approved', size: '6.0MB', img: 'https://picsum.photos/seed/brick_project/800/800', tags: ['Community'] },
      ],
    },
    {
      referenceId: 'PRD_310',
      publicSku: 'BTS-PAV-BEV-310',
      name: 'Urban Granite Bevel Paver',
      category: 'Paving',
      productType: 'Bevel',
      finish: null,
      collection: 'Urban Grid',
      tags: ['Paving', 'Bevel', 'External'],
      status: 'Active',
      publishStatus: 'Draft',
      pricingUnit: 'piece',
      sellPriceZar: 42,
      primaryImageUrl: 'https://picsum.photos/seed/paver_primary/800/800',
      galleryImageUrl: 'https://picsum.photos/seed/paver_gallery/800/800',
      faceImageUrl: 'https://picsum.photos/seed/paver_face/800/800',
      heroImageUrl: null,
      description: 'Granite-tone bevel paver for durable external paving systems and hardscape packages.',
      marketingCopy: '',
      latestTestReport: {
        name: 'urban-granite-bevel-paver-test-sheet.pdf',
        laboratoryName: 'Concrete Systems QA',
        methodStandard: 'Internal QA',
        reportReference: 'LAB-PAV-310-2026-03',
        testedAt: '2026-03-06T08:00:00.000Z',
        issuedAt: '2026-03-08T09:00:00.000Z',
      },
      specifications: {
        Material: 'Concrete Paving',
        Use: 'External Hardscape',
        Pack: 'Sold per piece / pallet',
      },
      testResults: [
        { type: 'Tested Length (mm)', value: 200, unit: 'mm' },
        { type: 'Tested Width (mm)', value: 100, unit: 'mm' },
        { type: 'Tested Height (mm)', value: 60, unit: 'mm' },
        { type: 'Dry Mass (kg)', value: 2.6, unit: 'kg' },
      ],
      dimensions: {
        lengthMm: 200,
        widthMm: 100,
        heightMm: 60,
        coverageOrientation: 'Length x Width',
        weightKg: 2.6,
      },
      packaging: {
        piecesPerPallet: 360,
        palletsPerTruck: 24,
      },
      supplierLink: {
        supplierKey: 'VND_003',
        locationKey: 'LOC_003',
        unitCostZar: 26.5,
        leadTimeDays: 18,
        minimumOrderQuantity: 250,
        paymentTerms: 'COD for first order',
        incoterms: 'EXW',
      },
      purchaseOrders: [],
      history: [
        { type: 'Product Created', occurredAt: '2026-03-03T10:00:00.000Z', action: 'Product Created', user: 'Inventory API' },
        { type: 'Status Changed', occurredAt: '2026-03-29T10:15:00.000Z', action: 'Supplier Delay Reflected', user: 'System', details: 'Urban Paving Systems delay applied to availability' },
      ],
      distributionChannels: [
        {
          channel: 'Meta Catalog',
          type: 'Catalog',
          connectionStatus: 'Connected',
          publicationStatus: 'Not Posted',
          syncMode: 'API',
          externalCatalogId: 'meta-catalog-paving-main',
        },
        {
          channel: 'Google Merchant Center',
          type: 'Catalog',
          connectionStatus: 'Connected',
          publicationStatus: 'Paused',
          syncMode: 'Manual',
          externalCatalogId: 'gmc-bts-main',
          lastSyncedAt: '2026-03-29T10:40:00.000Z',
        },
      ],
      assets: [
        { key: 'AST_310_PRIMARY', name: 'Urban Granite Primary', type: 'Image', role: 'primary_image', source: 'Direct Upload', protectionLevel: 'Protected Original', status: 'Approved', size: '6.8MB', img: 'https://picsum.photos/seed/paver_primary/800/800', tags: ['Primary', 'Paving'] },
        { key: 'AST_310_GALLERY', name: 'Urban Granite Gallery', type: 'Image', role: 'gallery_image', source: 'Direct Upload', protectionLevel: 'Managed Variant', status: 'Approved', size: '5.3MB', img: 'https://picsum.photos/seed/paver_gallery/800/800', tags: ['Gallery'] },
        { key: 'AST_310_FACE', name: 'Urban Granite Face', type: 'Image', role: 'face_image', source: 'Direct Upload', protectionLevel: 'Managed Variant', status: 'Approved', size: '4.0MB', img: 'https://picsum.photos/seed/paver_face/800/800', tags: ['Face'] },
        { key: 'AST_310_GENERATED', name: 'Urban Granite Studio Variant', type: 'Image', role: 'generated_image', source: 'Studio Published', protectionLevel: 'Publishable Variant', status: 'Review', size: '2.6MB', img: 'https://picsum.photos/seed/paver_generated/800/800', tags: ['Studio', 'Generated'] },
      ],
    },
    {
      referenceId: 'PRD_420',
      publicSku: 'BTS-BLK-BRZ-420',
      name: 'Graphite Breeze Block',
      category: 'Blocks',
      productType: 'Breeze',
      finish: null,
      collection: 'Airframe',
      tags: ['Blocks', 'Breeze', 'Screens'],
      status: 'Draft',
      publishStatus: 'Not Ready',
      pricingUnit: 'piece',
      sellPriceZar: null,
      primaryImageUrl: 'https://picsum.photos/seed/block_primary/800/800',
      galleryImageUrl: 'https://picsum.photos/seed/block_gallery/800/800',
      faceImageUrl: 'https://picsum.photos/seed/block_face/800/800',
      heroImageUrl: null,
      description: 'Architectural breeze block intended for privacy screens, layered facades, and ventilation walls.',
      marketingCopy: '',
      latestTestReport: {
        name: 'graphite-breeze-block-datasheet.pdf',
        laboratoryName: 'Structural Block Lab',
        methodStandard: 'Internal QA',
        reportReference: 'LAB-BLK-420-2026-03',
        testedAt: '2026-03-18T08:00:00.000Z',
        issuedAt: '2026-03-20T10:00:00.000Z',
      },
      specifications: {
        Material: 'Cast Concrete',
        Use: 'Screen Block',
      },
      testResults: [
        { type: 'Tested Length (mm)', value: 390, unit: 'mm' },
        { type: 'Tested Width (mm)', value: 140, unit: 'mm' },
        { type: 'Tested Height (mm)', value: 190, unit: 'mm' },
        { type: 'Dry Mass (kg)', value: 11.8, unit: 'kg' },
      ],
      dimensions: {
        lengthMm: 390,
        widthMm: 140,
        heightMm: 190,
        coverageOrientation: 'Length x Height',
        weightKg: 11.8,
      },
      packaging: {
        piecesPerPallet: 100,
        palletsPerTruck: 24,
      },
      supplierLink: {
        supplierKey: 'VND_004',
        locationKey: 'LOC_004',
        unitCostZar: 89,
        leadTimeDays: 0,
        minimumOrderQuantity: 120,
        paymentTerms: 'TBD',
        incoterms: 'TBD',
      },
      purchaseOrders: [],
      history: [
        { type: 'Product Created', occurredAt: '2026-03-04T10:00:00.000Z', action: 'Product Created', user: 'Inventory API' },
        { type: 'Status Changed', occurredAt: '2026-03-30T08:00:00.000Z', action: 'Supplier Onboarding Pending', user: 'System', details: 'Waiting for final supplier pack' },
      ],
      distributionChannels: [
        {
          channel: 'Meta Catalog',
          type: 'Catalog',
          connectionStatus: 'Connected',
          publicationStatus: 'Not Posted',
          syncMode: 'API',
          externalCatalogId: 'meta-catalog-blocks-main',
        },
        {
          channel: 'TikTok Shop',
          type: 'Marketplace',
          connectionStatus: 'Not Connected',
          publicationStatus: 'Not Posted',
          syncMode: 'Manual',
        },
      ],
      assets: [
        { key: 'AST_420_PRIMARY', name: 'Graphite Breeze Primary', type: 'Image', role: 'primary_image', source: 'Direct Upload', protectionLevel: 'Protected Original', status: 'Approved', size: '6.5MB', img: 'https://picsum.photos/seed/block_primary/800/800', tags: ['Primary', 'Block'] },
        { key: 'AST_420_GALLERY', name: 'Graphite Breeze Gallery', type: 'Image', role: 'gallery_image', source: 'Direct Upload', protectionLevel: 'Managed Variant', status: 'Approved', size: '5.1MB', img: 'https://picsum.photos/seed/block_gallery/800/800', tags: ['Gallery'] },
        { key: 'AST_420_FACE', name: 'Graphite Breeze Face', type: 'Image', role: 'face_image', source: 'Direct Upload', protectionLevel: 'Managed Variant', status: 'Approved', size: '3.8MB', img: 'https://picsum.photos/seed/block_face/800/800', tags: ['Face'] },
      ],
    },
  ],
} as const;

export const samplePriceListImport: CreatePriceListImportInput = {
  fileName: 'supplier-price-list-zar.json',
  sourceType: 'json',
  rows: [
    {
      publicSku: 'BTS-CLD-PRM-901',
      name: 'Sandstone Premium Cladding',
      category: 'Cladding',
      productType: 'Premium',
      finish: 'Smooth',
      collection: 'Sahara',
      description: 'Premium sandstone-inspired cladding for luxury exteriors.',
      sellPriceZar: 1380,
      unitCostZar: 910,
      linkedSupplierId: 'VND_001',
      pricingUnit: 'm2',
      lengthMm: 450,
      widthMm: 32,
      heightMm: 110,
      weightKg: 3.2,
      piecesPerPallet: 2000,
      boxesPerPallet: 40,
      palletsPerTruck: 24,
      primaryImageUrl: 'https://picsum.photos/seed/import_cladding_primary/800/800',
      galleryImageUrl: 'https://picsum.photos/seed/import_cladding_gallery/800/800',
      faceImageUrl: 'https://picsum.photos/seed/import_cladding_face/800/800',
      tags: ['Cladding', 'Premium'],
    },
    {
      publicSku: 'BTS-BLK-CEM-331',
      name: 'Ash Cement Block',
      category: 'Blocks',
      productType: 'Cement',
      collection: 'Core',
      description: 'Structural cement block for utility and support walls.',
      sellPriceZar: 56,
      unitCostZar: 33,
      linkedSupplierId: 'VND_004',
      pricingUnit: 'piece',
      lengthMm: 390,
      widthMm: 140,
      heightMm: 190,
      weightKg: 12.1,
      piecesPerPallet: 100,
      palletsPerTruck: 24,
      tags: ['Blocks', 'Cement'],
    },
  ],
};
