import type { CreatePriceListImportInput } from './contracts';

export const inventorySeedFixtures = {
  suppliers: [
    {
      key: 'VND_001',
      name: 'Global Tiles Co.',
      logo: 'https://picsum.photos/seed/globaltiles/100/100',
      status: 'Active',
      type: 'Manufacturer',
      capabilities: ['Ceramic', 'Porcelain', 'Large Format'],
      region: 'Italy / Emilia-Romagna',
      leadTimeDays: 35,
      leadTimeLabel: '4-6 Weeks',
      rating: 4.8,
      blocker: null,
      contacts: [
        { department: 'Sales', name: 'Marco Rossi', email: 'marco@globaltiles.it', phone: '+39 0536 123456', preferredChannel: 'Email', notes: 'Primary account manager' },
        { department: 'Accounts', name: 'Giulia Conti', email: 'accounts@globaltiles.it', phone: '+39 0536 112233', preferredChannel: 'Email', notes: 'Invoicing and statements' },
        { department: 'Dispatch', name: 'Luca Bianchi', email: 'logistics@globaltiles.it', phone: '+39 0536 654321', preferredChannel: 'Phone', notes: 'Warehouse and shipping coordination' },
      ],
      terms: { payment: 'Net 60', delivery: 'FOB Genoa', moq: '1 Pallet', currency: 'EUR', incoterms: 'FOB' },
      performance: { onTimeDelivery: 94, qualityScore: 98, returnRate: 1.2, priceCompetitiveness: 85 },
      workflowMilestones: { onboarded: true, linkedToProducts: true, poIssued: true, dispatchReady: true, claimsVerified: true },
      orders: [
        { id: 'PO-2024-001', date: '2024-03-15', status: 'Shipped', amount: 12450, type: 'PO' },
        { id: 'POD-2024-001', date: '2024-03-20', status: 'Delivered', amount: 12450, type: 'POD' },
      ],
      history: [
        { date: '2024-03-20', action: 'Price List Updated', user: 'System', details: 'Updated 142 SKU prices' },
        { date: '2024-03-10', action: 'Terms Renegotiated', user: 'Marcus Thorne', details: 'Payment terms changed from Net 30 to Net 60' },
      ],
      locations: [
        {
          key: 'LOC_001',
          label: 'Genoa Origin Hub',
          type: 'Supplier Origin',
          country: 'Italy',
          region: 'Emilia-Romagna',
          city: 'Genoa',
          latitude: 44.4056,
          longitude: 8.9463,
        },
      ],
    },
    {
      key: 'VND_002',
      name: 'Brick Masters Ltd.',
      logo: 'https://picsum.photos/seed/brickmasters/100/100',
      status: 'Restocking',
      type: 'Manufacturer',
      capabilities: ['Reclaimed Brick', 'Handmade Brick', 'Slips'],
      region: 'UK / Midlands',
      leadTimeDays: 18,
      leadTimeLabel: '2-3 Weeks',
      rating: 4.5,
      blocker: 'Production Delay on Red Blends',
      contacts: [
        { department: 'Sales', name: 'Sarah Jenkins', email: 'sarah@brickmasters.co.uk', phone: '+44 121 987 6543', preferredChannel: 'Phone', notes: 'Direct line' },
        { department: 'Dispatch', name: 'Mick Miller', email: 'dispatch@brickmasters.co.uk', phone: '+44 121 987 6545', preferredChannel: 'WhatsApp', notes: 'Best for quick updates' },
      ],
      terms: { payment: 'Net 30', delivery: 'DDP London', moq: '5 Pallets', currency: 'GBP', incoterms: 'DDP' },
      performance: { onTimeDelivery: 88, qualityScore: 92, returnRate: 2.5, priceCompetitiveness: 78 },
      workflowMilestones: { onboarded: true, linkedToProducts: true, poIssued: true, dispatchReady: false, claimsVerified: true },
      orders: [{ id: 'PO-2024-012', date: '2024-03-10', status: 'Delivered', amount: 4500, type: 'PO' }],
      history: [{ date: '2024-03-22', action: 'Status Changed to Restocking', user: 'System', details: 'Inventory below threshold' }],
      locations: [
        {
          key: 'LOC_002',
          label: 'Birmingham Dispatch Yard',
          type: 'Supplier Origin',
          country: 'United Kingdom',
          region: 'Midlands',
          city: 'Birmingham',
          latitude: 52.4862,
          longitude: -1.8904,
        },
      ],
    },
    {
      key: 'VND_003',
      name: 'Ceramic Solutions',
      logo: 'https://picsum.photos/seed/ceramicsolutions/100/100',
      status: 'Active',
      type: 'Distributor',
      capabilities: ['Mosaics', 'Feature Tiles', 'Grout'],
      region: 'Spain / Castellon',
      leadTimeDays: 10,
      leadTimeLabel: '1-2 Weeks',
      rating: 4.9,
      blocker: null,
      contacts: [{ department: 'Accounts', name: 'Elena Garcia', email: 'accounts@ceramicsol.es', phone: '+34 964 112233', preferredChannel: 'Email' }],
      terms: { payment: 'Net 45', delivery: 'EXW Castellon', moq: 'No MOQ', currency: 'EUR', incoterms: 'EXW' },
      performance: { onTimeDelivery: 99, qualityScore: 99, returnRate: 0.5, priceCompetitiveness: 92 },
      workflowMilestones: { onboarded: true, linkedToProducts: true, poIssued: true, dispatchReady: true, claimsVerified: true },
      orders: [{ id: 'PO-2024-005', date: '2024-03-01', status: 'Delivered', amount: 2100, type: 'PO' }],
      history: [{ date: '2024-03-05', action: 'New Catalog Imported', user: 'Elena Garcia', details: 'Added 45 new mosaic SKUs' }],
      locations: [
        {
          key: 'LOC_003',
          label: 'Castellon Mosaic Depot',
          type: 'Supplier Origin',
          country: 'Spain',
          region: 'Castellon',
          city: 'Castellon de la Plana',
          latitude: 39.9864,
          longitude: -0.0513,
        },
      ],
    },
    {
      key: 'VND_004',
      name: 'Stone & Clay Inc.',
      logo: 'https://picsum.photos/seed/stoneclay/100/100',
      status: 'Delayed',
      type: 'Wholesaler',
      capabilities: ['Natural Stone', 'Terracotta', 'Paving'],
      region: 'Turkey / Izmir',
      leadTimeDays: 63,
      leadTimeLabel: '8-10 Weeks',
      rating: 3.8,
      blocker: 'Customs Clearance Hold',
      contacts: [{ department: 'Export', name: 'Ahmet Yilmaz', email: 'export@stoneclay.com.tr', phone: '+90 232 444 5566', preferredChannel: 'Email' }],
      terms: { payment: '30% Deposit, 70% BL', delivery: 'CIF Felixstowe', moq: '1 Container', currency: 'USD', incoterms: 'CIF' },
      performance: { onTimeDelivery: 72, qualityScore: 85, returnRate: 4.2, priceCompetitiveness: 95 },
      workflowMilestones: { onboarded: true, linkedToProducts: true, poIssued: true, dispatchReady: false, claimsVerified: false },
      orders: [{ id: 'PO-2024-002', date: '2024-02-15', status: 'Shipped', amount: 35000, type: 'PO' }],
      history: [{ date: '2024-03-18', action: 'Shipment Delayed', user: 'System', details: 'Vessel delayed at port' }],
      locations: [
        {
          key: 'LOC_004',
          label: 'Izmir Stone Port',
          type: 'Supplier Origin',
          country: 'Turkey',
          region: 'Izmir',
          city: 'Izmir',
          latitude: 38.4237,
          longitude: 27.1428,
        },
      ],
    },
    {
      key: 'VND_005',
      name: 'Nordic Minimal',
      logo: 'https://picsum.photos/seed/nordic/100/100',
      status: 'Onboarding',
      type: 'Manufacturer',
      capabilities: ['Concrete Look', 'Terrazzo', 'Large Format'],
      region: 'Denmark / Copenhagen',
      leadTimeDays: 0,
      leadTimeLabel: 'TBD',
      rating: 0,
      blocker: 'Awaiting Tax Documents',
      contacts: [{ department: 'Onboarding', name: 'Lars Nielsen', email: 'lars@nordicminimal.dk', phone: '+45 33 11 22 33', preferredChannel: 'Email' }],
      terms: { payment: 'TBD', delivery: 'TBD', moq: 'TBD', currency: 'EUR', incoterms: 'TBD' },
      performance: { onTimeDelivery: 0, qualityScore: 0, returnRate: 0, priceCompetitiveness: 0 },
      workflowMilestones: { onboarded: true, linkedToProducts: false, poIssued: false, dispatchReady: false, claimsVerified: false },
      orders: [],
      history: [{ date: '2024-03-25', action: 'Onboarding Started', user: 'Marcus Thorne', details: 'Initial contact made' }],
      locations: [
        {
          key: 'LOC_005',
          label: 'Copenhagen Design Hub',
          type: 'Supplier Origin',
          country: 'Denmark',
          region: 'Copenhagen',
          city: 'Copenhagen',
          latitude: 55.6761,
          longitude: 12.5683,
        },
      ],
    },
  ],
  logisticsRateCards: [
    { key: 'RATE_001', supplierKey: 'VND_001', locationKey: 'LOC_001', currency: 'GBP', costPerKm: 1.35, sellPricePerKm: 2.1, fixedFee: 180, minimumCharge: 250 },
    { key: 'RATE_002', supplierKey: 'VND_002', locationKey: 'LOC_002', currency: 'GBP', costPerKm: 0.95, sellPricePerKm: 1.75, fixedFee: 90, minimumCharge: 140 },
    { key: 'RATE_003', supplierKey: 'VND_003', locationKey: 'LOC_003', currency: 'GBP', costPerKm: 1.1, sellPricePerKm: 1.95, fixedFee: 120, minimumCharge: 180 },
    { key: 'RATE_004', supplierKey: 'VND_004', locationKey: 'LOC_004', currency: 'GBP', costPerKm: 1.8, sellPricePerKm: 2.8, fixedFee: 240, minimumCharge: 320 },
    { key: 'RATE_005', supplierKey: 'VND_005', locationKey: 'LOC_005', currency: 'GBP', costPerKm: 1.25, sellPricePerKm: 2.05, fixedFee: 150, minimumCharge: 220 },
  ],
  products: [
    {
      referenceId: 'PRD_882',
      name: 'Slate Grey Tile',
      sku: 'BTS-SLT-882',
      productType: 'Tile',
      commercialCategory: 'Industrial',
      collection: 'Slate Technical',
      tags: ['Premium', 'Industrial', 'Commercial'],
      status: 'Active',
      publishStatus: 'Published',
      unit: 'm2',
      sellPrice: 45,
      primaryImageUrl: 'https://picsum.photos/seed/slate1/800/800',
      description: 'A premium industrial slate tile engineered for large-scale architectural installations.',
      marketingCopy: 'Premium slate geometry for technical facades and high-traffic specification work.',
      specifications: {
        Dimensions: '600x600x10mm',
        Material: 'Natural Slate',
        Finish: 'Matte / Honed',
        Weight: '8.5kg per tile',
      },
      dimensionsText: '600x600x10mm',
      weightKg: 8.5,
      reorderPoint: 500,
      supplierLinks: [
        { supplierKey: 'VND_001', locationKey: 'LOC_001', isDefault: true, unitCost: 22.5, currency: 'GBP', leadTimeDays: 35, minimumOrderQuantity: 1, paymentTerms: 'Net 60', incoterms: 'FOB' },
        { supplierKey: 'VND_003', locationKey: 'LOC_003', isDefault: false, unitCost: 24.1, currency: 'GBP', leadTimeDays: 10, minimumOrderQuantity: 1, paymentTerms: 'Net 45', incoterms: 'EXW' },
        { supplierKey: 'VND_004', locationKey: 'LOC_004', isDefault: false, unitCost: 25.8, currency: 'GBP', leadTimeDays: 63, minimumOrderQuantity: 20, paymentTerms: '30% Deposit', incoterms: 'CIF' },
      ],
      stockMovements: [
        { key: 'STK_882_001', type: 'Receipt', quantity: 1600, occurredAt: '2026-01-08T10:00:00.000Z', note: 'Opening stock receipt', referenceType: 'Seed', referenceId: 'OPENING-PRD-882' },
        { key: 'STK_882_002', type: 'Issue', quantity: 210, occurredAt: '2026-02-14T10:00:00.000Z', note: 'Customer fulfillment batch', referenceType: 'Order', referenceId: 'ORD-882-01' },
        { key: 'STK_882_003', type: 'Issue', quantity: 150, occurredAt: '2026-03-05T10:00:00.000Z', note: 'Customer fulfillment batch', referenceType: 'Order', referenceId: 'ORD-882-02' },
      ],
      history: [
        { type: 'Stock Updated', occurredAt: '2024-03-20T10:00:00.000Z', action: 'Stock Updated (+500)', user: 'Warehouse Bot' },
        { type: 'Price Adjusted', occurredAt: '2024-03-15T10:00:00.000Z', action: 'Price Adjusted', user: 'Marcus Thorne' },
      ],
      purchaseOrders: [
        {
          key: 'PO-2024-001',
          supplierKey: 'VND_001',
          locationKey: 'LOC_001',
          status: 'Shipped',
          orderedAt: '2024-03-15T09:00:00.000Z',
          currency: 'GBP',
          lines: [{ sku: 'BTS-SLT-882', quantity: 500, unitCost: 22.5 }],
          receipt: { key: 'GRN-2024-001', receivedAt: '2024-03-20T09:00:00.000Z', status: 'Received', note: 'Seeded opening receipt' },
        },
      ],
      assets: [
        {
          key: 'AST_001',
          name: 'Slate Grey Hero Original',
          type: 'Image',
          protectionLevel: 'Protected Original',
          size: '12.4MB',
          status: 'Approved',
          usage: ['Hero', 'Detail'],
          img: 'https://picsum.photos/seed/slate1/800/800',
          productId: 'PRD_882',
          productName: 'Slate Grey Tile',
          linkedProductIds: ['PRD_882'],
          linkedCampaignIds: ['CMP_001'],
          completeness: 100,
          is3DReady: false,
          tags: ['Premium', 'Industrial', 'High-Res'],
          workflowNode: 'asset.uploaded',
          linkProducts: ['PRD_882'],
          linkCampaigns: ['CMP_001'],
          usageRoles: ['hero', 'detail'],
        },
        {
          key: 'AST_002',
          name: 'Slate Grey - Web Variant',
          type: 'Image',
          protectionLevel: 'Publishable Variant',
          size: '1.2MB',
          status: 'Approved',
          usage: ['Gallery', 'Publishable Variant'],
          img: 'https://picsum.photos/seed/slate1_v/800/800',
          parentKey: 'AST_001',
          productId: 'PRD_882',
          productName: 'Slate Grey Tile',
          linkedProductIds: ['PRD_882'],
          linkedCampaignIds: ['CMP_001', 'CMP_003'],
          completeness: 100,
          is3DReady: false,
          tags: ['Optimized', 'Web'],
          watermarkProfile: 'Standard BTS',
          backgroundTransparent: false,
          workflowNode: 'variant.generated',
          linkProducts: ['PRD_882'],
          linkCampaigns: ['CMP_001', 'CMP_003'],
          usageRoles: ['gallery', 'publishable_variant'],
        },
        {
          key: 'AST_006',
          name: 'Slate Grey Installation Gallery',
          type: 'Image',
          protectionLevel: 'Managed Variant',
          size: '8.2MB',
          status: 'Approved',
          usage: ['Installation'],
          img: 'https://picsum.photos/seed/slate_install/800/800',
          productId: 'PRD_882',
          productName: 'Slate Grey Tile',
          linkedProductIds: ['PRD_882'],
          linkedCampaignIds: ['CMP_001'],
          completeness: 95,
          is3DReady: false,
          tags: ['Installation', 'Site'],
          workflowNode: 'asset.uploaded',
          linkProducts: ['PRD_882'],
          linkCampaigns: ['CMP_001'],
          usageRoles: ['installation'],
        },
        {
          key: 'AST_007',
          name: 'Slate Grey PBR Texture Set',
          type: '3D Asset',
          protectionLevel: 'Protected Original',
          size: '32.0MB',
          status: 'Approved',
          usage: ['3D Ready', 'Model'],
          img: 'https://picsum.photos/seed/slate_3d/800/800',
          productId: 'PRD_882',
          productName: 'Slate Grey Tile',
          linkedProductIds: ['PRD_882'],
          linkedCampaignIds: [],
          completeness: 90,
          is3DReady: true,
          tags: ['3D', 'PBR', 'Texture'],
          workflowNode: 'creative.approved',
          pipeline: { sourceUploaded: true, textureReady: true, previewAttached: true, modelReferenceAttached: true, conversionStatus: 'Processing' },
          linkProducts: ['PRD_882'],
          linkCampaigns: [],
          usageRoles: ['3d_ready', 'model', 'pbr_texture'],
        },
      ],
    },
    {
      referenceId: 'PRD_112',
      name: 'Emerald Glaze Brick',
      sku: 'BTS-EMR-112',
      productType: 'Brick',
      commercialCategory: 'Premium',
      collection: 'Emerald Glaze',
      tags: ['Gloss', 'Feature Wall', 'Brick'],
      status: 'Active',
      publishStatus: 'Ready',
      unit: 'piece',
      sellPrice: 12.5,
      primaryImageUrl: 'https://picsum.photos/seed/emerald3d/800/800',
      description: 'A glazed premium brick with a deep emerald sheen designed for signature feature walls.',
      marketingCopy: 'Luminous glazed clay for dramatic residential and hospitality surfaces.',
      specifications: {
        Dimensions: '215x65x15mm',
        Material: 'Glazed Clay',
        Finish: 'High Gloss',
        Weight: '0.8kg per brick',
      },
      dimensionsText: '215x65x15mm',
      weightKg: 0.8,
      reorderPoint: 1000,
      supplierLinks: [
        { supplierKey: 'VND_003', locationKey: 'LOC_003', isDefault: true, unitCost: 4.2, currency: 'GBP', leadTimeDays: 10, minimumOrderQuantity: 200, paymentTerms: 'Net 45', incoterms: 'EXW' },
        { supplierKey: 'VND_001', locationKey: 'LOC_001', isDefault: false, unitCost: 4.6, currency: 'GBP', leadTimeDays: 35, minimumOrderQuantity: 500, paymentTerms: 'Net 60', incoterms: 'FOB' },
      ],
      stockMovements: [
        { key: 'STK_112_001', type: 'Receipt', quantity: 5000, occurredAt: '2026-01-03T10:00:00.000Z', note: 'Opening stock receipt', referenceType: 'Seed', referenceId: 'OPENING-PRD-112' },
        { key: 'STK_112_002', type: 'Issue', quantity: 500, occurredAt: '2026-03-11T10:00:00.000Z', note: 'Customer fulfillment batch', referenceType: 'Order', referenceId: 'ORD-112-01' },
      ],
      history: [{ type: 'Asset Approved', occurredAt: '2024-03-22T10:00:00.000Z', action: '3D Model Approved', user: 'Sarah Chen' }],
      purchaseOrders: [],
      assets: [
        {
          key: 'AST_003',
          name: 'Emerald Glaze 3D Master',
          type: '3D Asset',
          protectionLevel: 'Protected Original',
          size: '45.8MB',
          status: 'Review',
          usage: ['Detail', '3D Ready', 'Model'],
          img: 'https://picsum.photos/seed/emerald3d/800/800',
          productId: 'PRD_112',
          productName: 'Emerald Glaze Brick',
          linkedProductIds: ['PRD_112'],
          linkedCampaignIds: [],
          completeness: 85,
          is3DReady: true,
          tags: ['3D', 'PBR', 'Master'],
          workflowNode: 'creative.approved',
          pipeline: { sourceUploaded: true, textureReady: true, previewAttached: true, modelReferenceAttached: true, conversionStatus: 'Processing' },
          linkProducts: ['PRD_112'],
          linkCampaigns: [],
          usageRoles: ['detail', '3d_ready', 'model'],
        },
        {
          key: 'AST_008',
          name: 'Emerald Glaze Hero',
          type: 'Image',
          protectionLevel: 'Protected Original',
          size: '9.1MB',
          status: 'Approved',
          usage: ['Hero'],
          img: 'https://picsum.photos/seed/emerald_hero/800/800',
          productId: 'PRD_112',
          productName: 'Emerald Glaze Brick',
          linkedProductIds: ['PRD_112'],
          linkedCampaignIds: ['CMP_001'],
          completeness: 100,
          is3DReady: false,
          tags: ['Gloss', 'Studio'],
          workflowNode: 'asset.uploaded',
          linkProducts: ['PRD_112'],
          linkCampaigns: ['CMP_001'],
          usageRoles: ['hero'],
        },
        {
          key: 'AST_009',
          name: 'Emerald Glaze Material Reference',
          type: 'Image',
          protectionLevel: 'Managed Variant',
          size: '4.6MB',
          status: 'Approved',
          usage: ['Detail'],
          img: 'https://picsum.photos/seed/emerald_ref/800/800',
          productId: 'PRD_112',
          productName: 'Emerald Glaze Brick',
          linkedProductIds: ['PRD_112'],
          linkedCampaignIds: [],
          completeness: 80,
          is3DReady: false,
          tags: ['Reference', 'Detail'],
          workflowNode: 'asset.uploaded',
          linkProducts: ['PRD_112'],
          linkCampaigns: [],
          usageRoles: ['detail', 'model_reference'],
        },
      ],
    },
    {
      referenceId: 'PRD_443',
      name: 'Rustic Red Brick',
      sku: 'BTS-RST-443',
      productType: 'Brick',
      commercialCategory: 'Lifestyle',
      collection: 'Reclaimed Heritage',
      tags: ['Rustic', 'Reclaimed', 'Brick'],
      status: 'Active',
      publishStatus: 'Ready',
      unit: 'piece',
      sellPrice: 8.9,
      primaryImageUrl: 'https://picsum.photos/seed/rustic_inst/800/800',
      description: 'A reclaimed clay brick with a deeply textured surface for warm heritage-led schemes.',
      marketingCopy: '',
      specifications: {
        Dimensions: '215x65x20mm',
        Material: 'Reclaimed Clay',
        Finish: 'Textured / Rough',
        Weight: '1.2kg per brick',
      },
      dimensionsText: '215x65x20mm',
      weightKg: 1.2,
      reorderPoint: 500,
      supplierLinks: [
        { supplierKey: 'VND_002', locationKey: 'LOC_002', isDefault: true, unitCost: 3.1, currency: 'GBP', leadTimeDays: 18, minimumOrderQuantity: 500, paymentTerms: 'Net 30', incoterms: 'DDP' },
        { supplierKey: 'VND_003', locationKey: 'LOC_003', isDefault: false, unitCost: 3.35, currency: 'GBP', leadTimeDays: 10, minimumOrderQuantity: 500, paymentTerms: 'Net 45', incoterms: 'EXW' },
        { supplierKey: 'VND_004', locationKey: 'LOC_004', isDefault: false, unitCost: 3.8, currency: 'GBP', leadTimeDays: 63, minimumOrderQuantity: 1000, paymentTerms: '30% Deposit', incoterms: 'CIF' },
        { supplierKey: 'VND_005', locationKey: 'LOC_005', isDefault: false, unitCost: 3.95, currency: 'GBP', leadTimeDays: 0, minimumOrderQuantity: 1000, paymentTerms: 'TBD', incoterms: 'TBD' },
      ],
      stockMovements: [
        { key: 'STK_443_001', type: 'Receipt', quantity: 250, occurredAt: '2026-01-18T10:00:00.000Z', note: 'Opening stock receipt', referenceType: 'Seed', referenceId: 'OPENING-PRD-443' },
        { key: 'STK_443_002', type: 'Issue', quantity: 130, occurredAt: '2026-03-10T10:00:00.000Z', note: 'Customer fulfillment batch', referenceType: 'Order', referenceId: 'ORD-443-01' },
      ],
      history: [{ type: 'Low Stock Alert', occurredAt: '2024-03-10T10:00:00.000Z', action: 'Low Stock Alert Triggered', user: 'System' }],
      purchaseOrders: [],
      assets: [
        {
          key: 'AST_005',
          name: 'Rustic Installation Shot',
          type: 'Image',
          protectionLevel: 'Protected Original',
          size: '8.5MB',
          status: 'Restricted',
          usage: ['Installation', 'Render'],
          img: 'https://picsum.photos/seed/rustic_inst/800/800',
          productId: 'PRD_443',
          productName: 'Rustic Red Brick',
          linkedProductIds: ['PRD_443'],
          linkedCampaignIds: ['CMP_001'],
          completeness: 95,
          is3DReady: false,
          tags: ['Lifestyle', 'On-Site'],
          workflowNode: 'asset.uploaded',
          linkProducts: ['PRD_443'],
          linkCampaigns: ['CMP_001'],
          usageRoles: ['installation', 'render'],
        },
        {
          key: 'AST_010',
          name: 'Rustic Placeholder Hero',
          type: 'Image',
          protectionLevel: 'Managed Variant',
          size: '2.1MB',
          status: 'Draft',
          usage: ['Hero'],
          img: 'https://picsum.photos/seed/rustic_placeholder/800/800',
          productId: 'PRD_443',
          productName: 'Rustic Red Brick',
          linkedProductIds: ['PRD_443'],
          linkedCampaignIds: [],
          completeness: 20,
          is3DReady: false,
          tags: ['Placeholder'],
          workflowNode: 'variant.generated',
          linkProducts: ['PRD_443'],
          linkCampaigns: [],
          usageRoles: ['hero'],
        },
      ],
    },
    {
      referenceId: 'PRD_501',
      name: 'Midnight Obsidian Slab',
      sku: 'BTS-OBS-501',
      productType: 'Stone',
      commercialCategory: 'Luxury',
      collection: 'Obsidian Atelier',
      tags: ['Luxury', 'Stone', 'Feature'],
      status: 'Active',
      publishStatus: 'Published',
      unit: 'slab',
      sellPrice: 120,
      primaryImageUrl: 'https://picsum.photos/seed/obsidian/800/800',
      description: 'A polished obsidian slab for rare luxury installations and statement surfaces.',
      marketingCopy: 'Volcanic gloss and architectural drama for ultra-premium interiors.',
      specifications: {
        Dimensions: '1200x600x20mm',
        Material: 'Volcanic Obsidian',
        Finish: 'Polished',
        Weight: '35kg per slab',
      },
      dimensionsText: '1200x600x20mm',
      weightKg: 35,
      reorderPoint: 10,
      supplierLinks: [
        { supplierKey: 'VND_004', locationKey: 'LOC_004', isDefault: true, unitCost: 45, currency: 'GBP', leadTimeDays: 63, minimumOrderQuantity: 4, paymentTerms: '30% Deposit', incoterms: 'CIF' },
      ],
      stockMovements: [
        { key: 'STK_501_001', type: 'Receipt', quantity: 20, occurredAt: '2026-02-01T10:00:00.000Z', note: 'Opening stock receipt', referenceType: 'Seed', referenceId: 'OPENING-PRD-501' },
        { key: 'STK_501_002', type: 'Issue', quantity: 5, occurredAt: '2026-03-25T10:00:00.000Z', note: 'Luxury showroom allocation', referenceType: 'Order', referenceId: 'ORD-501-01' },
      ],
      history: [{ type: 'Campaign Linked', occurredAt: '2024-03-25T10:00:00.000Z', action: 'Luxury Campaign Linked', user: 'Sarah Chen' }],
      purchaseOrders: [],
      assets: [
        {
          key: 'AST_011',
          name: 'Midnight Obsidian Hero',
          type: 'Image',
          protectionLevel: 'Protected Original',
          size: '10.4MB',
          status: 'Approved',
          usage: ['Hero'],
          img: 'https://picsum.photos/seed/obsidian/800/800',
          productId: 'PRD_501',
          productName: 'Midnight Obsidian Slab',
          linkedProductIds: ['PRD_501'],
          linkedCampaignIds: ['CMP_002'],
          completeness: 100,
          is3DReady: false,
          tags: ['Luxury', 'Hero'],
          workflowNode: 'asset.uploaded',
          linkProducts: ['PRD_501'],
          linkCampaigns: ['CMP_002'],
          usageRoles: ['hero'],
        },
        {
          key: 'AST_012',
          name: 'Midnight Obsidian Detail Texture',
          type: 'Image',
          protectionLevel: 'Managed Variant',
          size: '6.7MB',
          status: 'Approved',
          usage: ['Detail'],
          img: 'https://picsum.photos/seed/obsidian_detail/800/800',
          productId: 'PRD_501',
          productName: 'Midnight Obsidian Slab',
          linkedProductIds: ['PRD_501'],
          linkedCampaignIds: [],
          completeness: 90,
          is3DReady: false,
          tags: ['Texture', 'Detail'],
          workflowNode: 'asset.uploaded',
          linkProducts: ['PRD_501'],
          linkCampaigns: [],
          usageRoles: ['detail', 'detail_texture'],
        },
        {
          key: 'AST_013',
          name: 'Midnight Obsidian 3D Model',
          type: '3D Asset',
          protectionLevel: 'Protected Original',
          size: '40.1MB',
          status: 'Approved',
          usage: ['3D Ready', 'Model'],
          img: 'https://picsum.photos/seed/obsidian_3d/800/800',
          productId: 'PRD_501',
          productName: 'Midnight Obsidian Slab',
          linkedProductIds: ['PRD_501'],
          linkedCampaignIds: ['CMP_002'],
          completeness: 88,
          is3DReady: true,
          tags: ['3D', 'Model'],
          workflowNode: 'creative.approved',
          pipeline: { sourceUploaded: true, textureReady: true, previewAttached: false, modelReferenceAttached: true, conversionStatus: 'Complete' },
          linkProducts: ['PRD_501'],
          linkCampaigns: ['CMP_002'],
          usageRoles: ['3d_ready', 'model'],
        },
        {
          key: 'AST_014',
          name: 'Midnight Obsidian Luxury Variant',
          type: 'Image',
          protectionLevel: 'Publishable Variant',
          size: '1.8MB',
          status: 'Approved',
          usage: ['Campaign', 'Publishable Variant'],
          img: 'https://picsum.photos/seed/obsidian_variant/800/800',
          productId: 'PRD_501',
          productName: 'Midnight Obsidian Slab',
          linkedProductIds: ['PRD_501'],
          linkedCampaignIds: ['CMP_002'],
          completeness: 95,
          is3DReady: false,
          tags: ['Luxury', 'Campaign'],
          workflowNode: 'variant.generated',
          linkProducts: ['PRD_501'],
          linkCampaigns: ['CMP_002'],
          usageRoles: ['campaign', 'publishable_variant'],
        },
      ],
    },
  ],
} as const;

export const samplePriceListImport: CreatePriceListImportInput = {
  fileName: 'seeded-supplier-price-list.json',
  sourceType: 'json',
  rows: [
    {
      sku: 'BTS-SLT-882',
      name: 'Slate Grey Tile',
      productType: 'Tile',
      commercialCategory: 'Industrial',
      collection: 'Slate Technical',
      description: 'Updated supplier pricing row for Slate Grey Tile.',
      sellPrice: 45,
      unitCost: 22.5,
      currency: 'GBP',
      unit: 'm2',
      tags: ['Premium', 'Industrial', 'Commercial'],
    },
    {
      sku: 'BTS-NEW-901',
      name: 'Graphite Breeze Block',
      productType: 'Brick',
      commercialCategory: 'Premium',
      collection: 'Graphite Forms',
      description: 'A perforated architectural block for screened facades and statement partitions.',
      sellPrice: 18.5,
      unitCost: 7.4,
      currency: 'GBP',
      unit: 'piece',
      tags: ['Breeze Block', 'Facade'],
    },
  ],
};
